### PR TITLE
Remove CircleCI conf per PR #3

### PR DESCRIPTION
**Pull request by vanastassiou**
Resolves https://github.com/plotly/streambed/issues/12867

Addresses https://github.com/plotly/heroku-buildpack-python/pull/3

Not able to see where in https://circleci.com/gh/plotly/herokuish one would archive or delete the project, though; is that something we want to do?

### CODE REVIEW

**Comment by josegonzalez** [comment]
The [plotly/herokuish](https://github.com/plotly/herokuish) repo is still good (and actually what we want). It shouldn't be archived.

We will need to disable Circle on this repository though. Not sure how to do that...

**Comment by josegonzalez** [comment]
I think an org admin - @jkaplowitz ? - needs to modify [this page](https://circleci.com/gh/organizations/plotly/settings#projects) to disable this repository.

**Review by josegonzalez — APPROVED** [review]
💃 Approved once it's been disabled by an org admin in circleci (wait till thats confirmed please!)

**Comment by jkaplowitz** [comment]
@josegonzalez you're the only one following plotly/heroku-buildpack-python in circleci. I think you are better equipped to sever that link than I am (on the circleci side). I don't see where to do it in the UI even for projects that I am following.

I am a GH org admin for us, but isn't this linkage controlled from CircleCI? we certianly don't want to remove CircleCI from the GH org overall.

**Comment by josegonzalez** [comment]
We want to remove that project from the CircleCI org. I can't do so because I'm not a Github org admin, which is required for changing that in CircleCI apparently.

**Comment by jkaplowitz** [comment]
Can you point me to the right bit of the CircleCI user interface?

**Comment by jkaplowitz** [comment]
@josegonzalez CircleCI says "Projects are only tested if they have a follower." So you should unfollow the project in CircleCI and I'll remove the webhook from the GH side of the integration.

**Comment by jkaplowitz** [comment]
@josegonzalez I just removed the webhook and the deploy key from the GH side. I think you can clean it up from the CircleCI side by unfollowing, and I think @vanastassiou can proceed with this PR.

**Comment by josegonzalez** [comment]
Unfollowed!

**Pull request merged**
