### PR TITLE
Airgap upstream fix

### PR DESCRIPTION
**Pull request by BRONSOLO**
### Context:

Resolves: https://github.com/plotly/streambed/issues/13930
Upstream issue opened [here](https://github.com/heroku/heroku-buildpack-python/issues/916) related to https://github.com/plotly/heroku-buildpack-python/pull/21/commits/590276ca22834251b96d29cd7bb1072e9e52611b. 

### Test Plan:

- [x] Successfully deploy an Dash App on an Airgapped environment using this buildpack

### Changelog:

- [x] updates added to this PR

image

### CODE REVIEW

**Comment by BRONSOLO** [comment]
@scjody please review

**Review by scjody — COMMENTED** [review]
Looks good! I'm curious why we don't _always_ use the `get-pip.py` shipped with the buildpack now, to reduce the number of things we depend on from Heroku. Is there a reason that theirs might be better or more up to date?

**Comment by BRONSOLO** [comment]
>Is there a reason that theirs might be better or more up to date?

Based on the summary provided [here](https://github.com/heroku/heroku-buildpack-python/pull/840#issue-316642188), the motivation to take this approach from upstream is as follows: 

1.  _binaries belong on S3 versus in the buildpack_
2. _updates to this file can be rolled out quickly and easily_
3. _[this updated get-pip.py] will resolve issues building Python 3.7.4 and 3.6.9 on all stacks_

It seems to me that point 3 above is only point that is of concern to us and, even in that case, vendoring the latest get-pip.py will bring in the fixes necessary for the mentioned Python versions. 

Perhaps a better approach on our end is to:

1) always use the vendored get-pip.py regardless if deploying on an airgapped vs. non-airgapped system 
2) add a note to our release process / readme of our buildpack fork to update our vendored get-pip.py every release so as to benefit from any needed fixes (as in point 3 above). 

@scjody I can make the above changes if you agree.

**Comment by BRONSOLO** [comment]
@scjody updates made, please review!

**Review by scjody — APPROVED** [review]
💃

**Pull request merged**
