### PR TITLE
Update pip from 19.3.1 to 20.2.4

### PR DESCRIPTION
**Pull request by vanastassiou**
https://github.com/plotly/streambed/issues/14939

The updated `get-pip.py` was generated as follows:
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
```
Tested as follows:
1. - [x] Update `dds-vendor` `Dockerfile` to install new `pip` version
1. - [x] Install Dash Enterprise using the above `dds-vendor` image
1. - [x] Deploy a Dash app with a `.buildpacks` file containing `https://github.com/plotly/heroku-buildpack-python.git#update-pip`
1. - [x] `exec` into Dash app container and `/app/.heroku/python/bin/pip --version`

### CODE REVIEW

**Comment by vanastassiou** [comment]
@gzork please review.

**Comment by vanastassiou** [comment]
@BRONSOLO just wanted to check in with you re the test steps and confirm the container to test the `pip` version in, and how.

**Comment by BRONSOLO** [comment]
Hey @vanastassiou the testing steps look good but additional changes are needed for this PR in the end as we're vendoring the pip version being used: 

1) We set `pip==9.02` in the dds-vendor Docker file so that will need to be bumped to the intended version (e.g., `pip==20.2.4`) here: https://github.com/plotly/dds-vendor/blob/a8bb3d389903e0db6331bad38476556db9aa21ad/Dockerfile#L5

2) We will then need to reference this vendored version by changing  `pip-9.0.2-py2.py3-none-any.whl` to `pip-20.2.4-py2.py3-none-any.whl` here: https://github.com/plotly/heroku-buildpack-python/blob/e969daae247b5c02580465e53512000439bb0329/bin/steps/python#L168 

3) Lastly, the version that will be used to compare pip against to trigger an upgrade can be updated (e.g., to `20.2.4`) here: https://github.com/plotly/heroku-buildpack-python/blob/e969daae247b5c02580465e53512000439bb0329/bin/compile#L67

Given the change to dds-vendor in 1), the image will need to be updated within the Replicated yaml for testing as well.

**Comment by vanastassiou** [comment]
@tarzzz please review.

**Comment by chriddyp** [comment]
>  /app/.heroku/python/bin/python "$PIP_DIR/get-pip.py" --no-index "$GET_PIP_PYPI_INDEX_URL/pip/pip-9.0.2-py2.py3-none-any.whl" "$GET_PIP_PYPI_INDEX_URL/setuptools/setuptools-39.0.1-py2.py3-none-any.whl" "$GET_PIP_PYPI_INDEX_URL/wheel/wheel-0.31.1-py2.py3-none-any.whl" &> /dev/null 

Hey folks - I was reading through the heroku-buildpack-python [CHANGELOG](https://github.com/heroku/heroku-buildpack-python/blob/main/CHANGELOG.md) tonight and came across this: https://github.com/heroku/heroku-buildpack-python/pull/1007. If we're updgrading the heroku buildpack too, then maybe the way we upgrade `pip` needs to change to use `pip` instead of `get-pip.py`? I don't know our own codebase at all, but just thought I'd share if helpful.

**Comment by vanastassiou** [comment]
@chriddyp Upstream does opt to use `pip` instead of `get-pip.py`, but I've been finding the sync with upstream rather complicated so was planning to split the sync out into a separate issue to ensure that `pip` was upgraded in a timely manner.

**Review by tarzzz — APPROVED** [review]
💃

**Comment by tarzzz** [comment]
@vanastassiou Can you please add a note in https://github.com/plotly/streambed/issues/15131 about Chris' comment so that it's not lost when we merge this PR.?

**Pull request merged**
